### PR TITLE
Shapes

### PR DESCRIPTION
**Pull request by illiabovtriuk**
Now it is done I believe

### CODE REVIEW

**Comment by aualbert** [comment]
There are conflits to resolve before merging. I will take care of it.

**Comment by aualbert** [comment]
It does not work when running:
TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by illiabovtriuk** [comment]
I guess you pass X and Y to function. Put NX and NY
It works i have tested it

ср, 23 нояб. 2022 г. в 08:55, aualbert ***@***.***>:

**Comment by aualbert** [comment]
If this is the case, please change it.

**Comment by aualbert** [comment]
I will review thé code once it is working

**Comment by illiabovtriuk** [comment]
It is working, but function have sizes as input parameters, not meshgrid

ср, 23 лист. 2022, 12:05 користувач aualbert ***@***.***>
пише:

**Comment by aualbert** [comment]
Please, make the appropriate changes and fix your code. I wont review if it throws an error when i type python main.py.

**Pull request closed without merging**
